### ISSUE TITLE
Does it lets add anime to anilist watchlist?

### ISSUE THREAD

**Issue by animemandir** [Anivue/Anivue#3]
This is an amazing project !
I suggest you add a analytics tracker.
Instead of making users redirecting to Crunchyroll, can you make them redirect to https://ani-toons.vercel.app/
It is a simple nextjs project am working on, it's not complete yet but does a decent job, it has no trackers or ads and is safe.
would love to contribute to anivue too.

**Comment by metafates** [comment]
Hi, thanks for the offer and your interest in the project. 
No, you can only add anime, manga and characters to **favorites**. Unfortunately I'm no longer developing anivue. Right now I'm doing something like anivue **v2**, independent of third party APIs, but don't know when it will be ready

**Comment by metafates** [comment]
> This is an amazing project ! I suggest you add a analytics tracker. Instead of making users redirecting to Crunchyroll, can you make them redirect to https://ani-toons.vercel.app/ It is a simple nextjs project am working on, it's not complete yet but does a decent job, it has no trackers or ads and is safe. would love to contribute to anivue too.

Hi, thanks for the offer and your interest in the project. 
No, you can only add anime, manga and characters to **favorites**. Unfortunately I'm no longer developing anivue. Right now I'm doing something like anivue **v2**, independent of third party APIs, but don't know when it will be ready

**Comment by animemandir** [comment]
Independent of any api??  !! That would require a huge db. How you gonna do it? a fullstack?

**Comment by metafates** [comment]
Ye, it will be a full-stack app. As for the db - I wrote a somewhat powerful web-scraper which uses multiple sources to populate and update my database automatically. Server and scraper are almost ready, so i'll start working on the frontend soon
