### ISSUE TITLE
Login is not working...

### ISSUE THREAD

**Issue by animemandir** [Anivue/Anivue#5]
Hey, login is not working, i think the app is not catching client_id and token.
Those are stored in browser right?

**Comment by metafates** [comment]
Hey, yes I'm aware of that. I should probably just update the app token

**Comment by metafates** [comment]
Nevermind, I looked at the code and it's an unsecure disaster lol. I removed authentication

**Comment by metafates** [comment]
I actually have no intention to continue with this project since it was something I could just practice on. It's very old and full of spaghetti code, sadly
